global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s 

scrape_configs:
  - job_name: prometheus
scrape_interval: 5s
static_configs:
  - targets:
  - prometheus:9090

- job_name: cadvisor
scrape_interval: 5s
static_configs:
 - targets:
 - cadvisor:8081